// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: dash_3.5inch

#ifndef UI_NORMAL_H
#define UI_NORMAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Normal
extern void ui_Normal_screen_init(void);
extern void ui_Normal_screen_destroy(void);
extern lv_obj_t * ui_Normal;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Spinner3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Normal;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

