// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: dash_3.5inch

#include "../ui.h"

lv_obj_t * uic_RAW_sensor;
lv_obj_t * ui_RAWsensor = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_rpmVALUE = NULL;
lv_obj_t * ui_speedVALUE = NULL;
lv_obj_t * ui_engineTempVALUE = NULL;
lv_obj_t * ui_Labelone = NULL;
lv_obj_t * ui_AmbientTempVALUE = NULL;
lv_obj_t * ui_Labelone1 = NULL;
lv_obj_t * ui_pulseVALUE = NULL;
lv_obj_t * ui_throttleVALUE = NULL;
lv_obj_t * ui_mapCyl1VALUE = NULL;
lv_obj_t * ui_mapCyl2VALUE = NULL;
lv_obj_t * ui_fuelLevelVALUE1 = NULL;
lv_obj_t * ui_Labelone2 = NULL;
// event funtions

// build funtions

void ui_RAWsensor_screen_init(void)
{
    ui_RAWsensor = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RAWsensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RAWsensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RAWsensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_RAWsensor);
    lv_image_set_src(ui_Image12, &ui_img_1414997601);
    lv_obj_set_width(ui_Image12, lv_pct(27));
    lv_obj_set_height(ui_Image12, lv_pct(22));
    lv_obj_set_x(ui_Image12, 222);
    lv_obj_set_y(ui_Image12, 9);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_image_create(ui_RAWsensor);
    lv_image_set_src(ui_Image10, &ui_img_pngegg_png);
    lv_obj_set_width(ui_Image10, lv_pct(32));
    lv_obj_set_height(ui_Image10, lv_pct(7));
    lv_obj_set_x(ui_Image10, 207);
    lv_obj_set_y(ui_Image10, 106);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_RAWsensor);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 31);
    lv_obj_set_height(ui_Spinner1, 47);
    lv_obj_set_x(ui_Spinner1, 246);
    lv_obj_set_y(ui_Spinner1, 13);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_rpmVALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_rpmVALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmVALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmVALUE, 18);
    lv_obj_set_y(ui_rpmVALUE, 27);
    lv_label_set_text(ui_rpmVALUE, "rpm= 0000");
    lv_obj_set_style_text_color(ui_rpmVALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmVALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmVALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedVALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_speedVALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedVALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedVALUE, 18);
    lv_obj_set_y(ui_speedVALUE, 50);
    lv_label_set_text(ui_speedVALUE, "SPEED");
    lv_obj_set_style_text_color(ui_speedVALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedVALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedVALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_engineTempVALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_engineTempVALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_engineTempVALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_engineTempVALUE, 18);
    lv_obj_set_y(ui_engineTempVALUE, 69);
    lv_label_set_text(ui_engineTempVALUE, "tempEngine");
    lv_obj_set_style_text_color(ui_engineTempVALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_engineTempVALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_engineTempVALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelone = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_Labelone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelone, 16);
    lv_obj_set_y(ui_Labelone, 2);
    lv_label_set_text(ui_Labelone, "Direct from bike");
    lv_obj_set_style_text_color(ui_Labelone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelone, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmbientTempVALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_AmbientTempVALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmbientTempVALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AmbientTempVALUE, 18);
    lv_obj_set_y(ui_AmbientTempVALUE, 89);
    lv_label_set_text(ui_AmbientTempVALUE, "tempAmbient");
    lv_obj_set_style_text_color(ui_AmbientTempVALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AmbientTempVALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AmbientTempVALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelone1 = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_Labelone1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelone1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelone1, 12);
    lv_obj_set_y(ui_Labelone1, 143);
    lv_label_set_text(ui_Labelone1, "Direct from CAN sensor Hub ");
    lv_obj_set_style_text_color(ui_Labelone1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelone1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelone1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pulseVALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_pulseVALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pulseVALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pulseVALUE, 18);
    lv_obj_set_y(ui_pulseVALUE, 172);
    lv_label_set_text(ui_pulseVALUE, "injector pulse width ");
    lv_obj_set_style_text_color(ui_pulseVALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pulseVALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pulseVALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_throttleVALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_throttleVALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_throttleVALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_throttleVALUE, 18);
    lv_obj_set_y(ui_throttleVALUE, 197);
    lv_label_set_text(ui_throttleVALUE, "throttle position ");
    lv_obj_set_style_text_color(ui_throttleVALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_throttleVALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_throttleVALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mapCyl1VALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_mapCyl1VALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mapCyl1VALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mapCyl1VALUE, 18);
    lv_obj_set_y(ui_mapCyl1VALUE, 222);
    lv_label_set_text(ui_mapCyl1VALUE, "cylinder one map");
    lv_obj_set_style_text_color(ui_mapCyl1VALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mapCyl1VALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mapCyl1VALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mapCyl2VALUE = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_mapCyl2VALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mapCyl2VALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mapCyl2VALUE, 18);
    lv_obj_set_y(ui_mapCyl2VALUE, 248);
    lv_label_set_text(ui_mapCyl2VALUE, "cylinder two map");
    lv_obj_set_style_text_color(ui_mapCyl2VALUE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mapCyl2VALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mapCyl2VALUE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelLevelVALUE1 = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_fuelLevelVALUE1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuelLevelVALUE1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuelLevelVALUE1, 18);
    lv_obj_set_y(ui_fuelLevelVALUE1, 110);
    lv_label_set_text(ui_fuelLevelVALUE1, "fuel Level");
    lv_obj_set_style_text_color(ui_fuelLevelVALUE1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelLevelVALUE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelLevelVALUE1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelone2 = lv_label_create(ui_RAWsensor);
    lv_obj_set_width(ui_Labelone2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelone2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelone2, 13);
    lv_obj_set_y(ui_Labelone2, 296);
    lv_label_set_text(ui_Labelone2, "bluetooth wheel state");
    lv_obj_set_style_text_color(ui_Labelone2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelone2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelone2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_RAW_sensor = ui_RAWsensor;

}

void ui_RAWsensor_screen_destroy(void)
{
    if(ui_RAWsensor) lv_obj_del(ui_RAWsensor);

    // NULL screen variables
    uic_RAW_sensor = NULL;
    ui_RAWsensor = NULL;
    ui_Image12 = NULL;
    ui_Image10 = NULL;
    ui_Spinner1 = NULL;
    ui_rpmVALUE = NULL;
    ui_speedVALUE = NULL;
    ui_engineTempVALUE = NULL;
    ui_Labelone = NULL;
    ui_AmbientTempVALUE = NULL;
    ui_Labelone1 = NULL;
    ui_pulseVALUE = NULL;
    ui_throttleVALUE = NULL;
    ui_mapCyl1VALUE = NULL;
    ui_mapCyl2VALUE = NULL;
    ui_fuelLevelVALUE1 = NULL;
    ui_Labelone2 = NULL;

}
