// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: dash_3.5inch

#ifndef UI_RAWSENSOR_H
#define UI_RAWSENSOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RAWsensor
extern void ui_RAWsensor_screen_init(void);
extern void ui_RAWsensor_screen_destroy(void);
extern lv_obj_t * ui_RAWsensor;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_rpmVALUE;
extern lv_obj_t * ui_speedVALUE;
extern lv_obj_t * ui_engineTempVALUE;
extern lv_obj_t * ui_Labelone;
extern lv_obj_t * ui_AmbientTempVALUE;
extern lv_obj_t * ui_Labelone1;
extern lv_obj_t * ui_pulseVALUE;
extern lv_obj_t * ui_throttleVALUE;
extern lv_obj_t * ui_mapCyl1VALUE;
extern lv_obj_t * ui_mapCyl2VALUE;
extern lv_obj_t * ui_fuelLevelVALUE1;
extern lv_obj_t * ui_Labelone2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RAW_sensor;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

