// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: dash_3.5inch

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_rpmVALUE;
extern lv_obj_t * ui_Container1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

