// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: dash_3.5inch

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);

    ui_Spinner1 = lv_spinner_create(ui_Screen1);
    lv_spinner_set_anim_params(ui_Spinner1, 10000U, 200U);

    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 26);
    lv_obj_set_y(ui_Spinner1, -46);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label1, -120);
    lv_obj_set_y(ui_Label1, -211);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "rpm=");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label2, -71);
    lv_obj_set_y(ui_Label2, -210);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "0000");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Spinner1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;

}
