// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: dash_3.5inch

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_rpmVALUE = NULL;
lv_obj_t * ui_Container1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x7C090F), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image12, &ui_img_1414997601);
    lv_obj_set_width(ui_Image12, lv_pct(27));
    lv_obj_set_height(ui_Image12, lv_pct(22));
    lv_obj_set_x(ui_Image12, 101);
    lv_obj_set_y(ui_Image12, 231);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 213);
    lv_obj_set_height(ui_Button1, 42);
    lv_obj_set_x(ui_Button1, 78);
    lv_obj_set_y(ui_Button1, 110);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x130EFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 217);
    lv_obj_set_height(ui_Panel4, 57);
    lv_obj_set_x(ui_Panel4, -43);
    lv_obj_set_y(ui_Panel4, -197);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFF000D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 208);
    lv_obj_set_height(ui_Button2, 44);
    lv_obj_set_x(ui_Button2, 13);
    lv_obj_set_y(ui_Button2, 420);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image10, &ui_img_pngegg_png);
    lv_obj_set_width(ui_Image10, lv_pct(32));
    lv_obj_set_height(ui_Image10, lv_pct(7));
    lv_obj_set_x(ui_Image10, 85);
    lv_obj_set_y(ui_Image10, 330);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen1);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 67);
    lv_obj_set_height(ui_Spinner1, 47);
    lv_obj_set_x(ui_Spinner1, 143);
    lv_obj_set_y(ui_Spinner1, 258);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_rpmVALUE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpmVALUE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmVALUE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmVALUE, 25);
    lv_obj_set_y(ui_rpmVALUE, 173);
    lv_label_set_text(ui_rpmVALUE, "200000");
    lv_obj_set_style_bg_color(ui_rpmVALUE, lv_color_hex(0x1F8490), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmVALUE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 265);
    lv_obj_set_height(ui_Container1, 141);
    lv_obj_set_x(ui_Container1, 18);
    lv_obj_set_y(ui_Container1, 212);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image12 = NULL;
    ui_Button1 = NULL;
    ui_Panel4 = NULL;
    ui_Button2 = NULL;
    ui_Image10 = NULL;
    ui_Spinner1 = NULL;
    ui_rpmVALUE = NULL;
    ui_Container1 = NULL;

}
