// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: dash_3.5inch

#include "../ui.h"

lv_obj_t * uic_Normal;
lv_obj_t * ui_Normal = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Spinner3 = NULL;
// event funtions

// build funtions

void ui_Normal_screen_init(void)
{
    ui_Normal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Normal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Normal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Normal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Normal);
    lv_image_set_src(ui_Image1, &ui_img_rear_wheel_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 172
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 259
    lv_obj_set_x(ui_Image1, 3);
    lv_obj_set_y(ui_Image1, 2);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Normal);
    lv_image_set_src(ui_Image2, &ui_img_front_wheel_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 54
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 426);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Normal);
    lv_image_set_src(ui_Image3, &ui_img_ecu_warning__1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_Image3, 273);
    lv_obj_set_y(ui_Image3, 3);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Normal);
    lv_image_set_src(ui_Image4, &ui_img_fi_orange_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_Image4, 245);
    lv_obj_set_y(ui_Image4, 92);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner3 = lv_spinner_create(ui_Normal);
    //lv_spinner_set_anim_params(ui_Spinner3, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 137);
    lv_obj_set_height(ui_Spinner3, 101);
    lv_obj_set_x(ui_Spinner3, 120);
    lv_obj_set_y(ui_Spinner3, 179);
    lv_obj_remove_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    uic_Normal = ui_Normal;

}

void ui_Normal_screen_destroy(void)
{
    if(ui_Normal) lv_obj_del(ui_Normal);

    // NULL screen variables
    uic_Normal = NULL;
    ui_Normal = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Spinner3 = NULL;

}
