# DO NOT EDIT THIS FILE --- This file is a managed file, do not edit it directly.

set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ".elf")

target_compile_options(${PROJECT_NAME} PUBLIC
    ${CPU_FLAGS}
    ${CC_SECURE}
    # Compiler flags specific to Debug build type
    $<$<CONFIG:Debug>:
      $<$<COMPILE_LANGUAGE:C>: 
        --specs=nano.specs
        -std=gnu11
        -g3
        -O0
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        --specs=nano.specs
        -std=gnu++14
        -g3
        -O0
        -fno-use-cxa-atexit
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        --specs=nano.specs
        -g3
        -x
        assembler-with-cpp
      >
    >

)

target_include_directories(${PROJECT_NAME} PUBLIC 
    "${CMAKE_CURRENT_SOURCE_DIR}/Core/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/UI_LOGIC"
    "${CMAKE_CURRENT_SOURCE_DIR}/Core/Inc/User_Libs"
    "${CMAKE_CURRENT_SOURCE_DIR}/Debug"
    "${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/User_Libs"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/lvgl"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/UI_Squareline"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32H7xx_HAL_Driver/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Device/ST/STM32H7xx/Include"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Include"
)

target_compile_definitions(${PROJECT_NAME} PUBLIC 
    # Symbols specific to Debug build type
    $<$<CONFIG:Debug>: 
      $<$<COMPILE_LANGUAGE:C>: 
        DEBUG
        USE_PWR_LDO_SUPPLY
        USE_HAL_DRIVER
        STM32H743xx
      >

      $<$<COMPILE_LANGUAGE:CXX>: 
        DEBUG
        USE_PWR_LDO_SUPPLY
        USE_HAL_DRIVER
        STM32H743xx
      >
    
      $<$<COMPILE_LANGUAGE:ASM>: 
        DEBUG
      >
    >

    
)

target_link_options(${PROJECT_NAME} PUBLIC 
    ${CPU_FLAGS}
    ${CC_SECURE}

    # Linker flags specific to Debug build type
    $<$<CONFIG:Debug>: 
        --specs=nano.specs
        -T${CMAKE_CURRENT_BINARY_DIR}/STM32H743IITX_FLASH.ld
        --specs=nosys.specs
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.map
        -static
        -Wl,--no-warn-execstack
        -Wl,-z,noexecstack
    >

)
# Clean .map file
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/${PROJECT_NAME}.map")
